# Generated by Django 4.0.6 on 2022-12-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_products_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='added_date',
            field=models.DateField(),
        ),
    ]
